name: Build

on:
  push:
  pull_request:
    types:
      - opened
      - edited
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.201

    - name: InitNuget
      run: dotnet nuget  add source https://api.bintray.com/nuget/eventuateio-oss/eventuateio-dotnet-snapshots

    - name: Build
      run: ./test.sh
            
    - name: Dump Mongo logs
      uses: jwalton/gh-docker-logs@v1
      with:
        images: 'mongo'
        # Only show last 100 lines of each
        tail: '100'
      
    - name: Build Tests
      run: dotnet build EndToEndTests/EndToEndTests.csproj
      
    - name: Run Tests
      run: dotnet test EndToEndTests/EndToEndTests.csproj
      
      
      
      
